name: test GitHub Action
on:
  workflow_dispatch:


jobs:
  testjob:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: wechuli/prepostactions@main
      - run: node --version
 
