name: test GitHub Action
on:
  workflow_dispatch:


jobs:
  testjob:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: wechuli/actionsutils@main
      - uses: wechuli/actionsutils@main
        with:
          tasks: 'context,oidctoken,envs'
          create-artifact: true
